name: Assayo

on:
  pull_request:
    types: [closed]
  push:
    tags:
      - '*'
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create git log report
      uses: bakhirev/assayo@546e2214bf3e2b79492ccd95148b7004d5422c54
      with:
        add_file_info: true
